apiVersion: v1
kind: Service
metadata:
  name: app-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
spec:
  type: LoadBalancer
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000