apiVersion: apps/v1
kind: Deployment

metadata:
  name: python-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
      
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python-app
          image: 
          ports:
            - containerPort: 8000
          