apiVersion: apps/v1
kind: Deployment

metadata:
  name: python-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
      
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python-app
          image: 017520465419.dkr.ecr.us-east-1.amazonaws.com/repo:latest
          ports:
            - containerPort: 8088
          