pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
        AWS_DEFAULT_REGION = "us-east1"
    }

    stages {
        stage('ci') {
            steps {
                

                // Get some code from a GitHub repository
                git branch: 'main', url: 'https://github.com/mennahasan7/final-project.git'

                sh "cd hello-world-app"
                sh "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 017520465419.dkr.ecr.us-east-1.amazonaws.com "   
                sh "docker build -t repo ."
                sh "docker tag repo:latest 017520465419.dkr.ecr.us-east-1.amazonaws.com/repo:latest"
                sh "docker push 017520465419.dkr.ecr.us-east-1.amazonaws.com/repo:latest"
            }

        }
        stage('cd'){
            steps{
                  sh """
                  aws eks --region "us-east-1" update-kubeconfig --name eks-cluster
                  kubectl apply -f deployment.yaml 
                  kubectl apply -f service.yaml 
                  """
            }

        }
    }
}
